#Site info
title: The Collaborative FRC Resources
mobile_title: CFRCR



#Site config
main_menu: #A list of the menu items for the top of the page
  -
    text: Home
    url: /
    current_if_is: / #The url of the page has to be "/" for the Home link to be darkened
  -
    text: About
    url: /about/
    current_if_is: /about/
  -
    text: Glossary
    url: /glossary/
    current_if_contains: /glossary/ #The url of the page has to contain "/glossary/" for the Glossary link to be darkened
  -
    text: Resources
    url: /resources/
    current_if_contains: /resources/

collections: #A list of all custom jekyll collections aand their variables
  glossary: #Useful terms
    output: true
  rsrc_indices:
    output: true
  rsrc-git_basics-cli:
    output: true
  rsrc-contributing_to_cfrcr:
    output: true

defaults: #Default values for page variables
  - #All pages
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - #Terms in the glossary
    scope:
      path: ""
      type: glossary
    values:
      layout: "term"
      permalink: /:collection/:path/
  - #Resources indices
    scope:
      path: ""
      type: rsrc_indices
    values:
      layout: "resource_index"
      permalink: /resources/:path/
  -
    scope:
      path: ""
      type: rsrc-git_basics-cli
    values:
      permalink: /resources/git_basics-cli/:path/
      layout: resource
  -
    scope:
      path: ""
      type: rsrc-contributing_to_cfrcr
    values:
      permalink: /resources/contributing_to_cfrcr/:path/
      layout: resource



# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
keep_files: [build.log]
