#Site info
title: The Collaborative FRC Resources
mobile_title: CFRCR



#Site setup
main_menu:
  -
    text: Home
    url: /
    current_if_is: / #The url of the page has to be "/" for the Home link to be darkened
  -
    text: About
    url: /about/
    current_if_is: /about/
  -
    text: Collections
    url: /collections/
    current_if_contains: /collections/
  -
    text: Documents
    url: /documents/
    current_if_contains: /documents/
  -
    text: Glossary
    url: /glossary/
    current_if_contains: /glossary/ #The url of the page has to contain "/glossary/" for the Glossary link to be darkened

collections: #A list of all custom jekyll collections aand their variables
  collections: #Collections of different kinds of resources
    output: true
  documents: #Resource documents that can be used in collections or viewed individually
    output: true
  glossary: #Useful terms
    output: true

defaults: #Default values for page variables
  - #All pages
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - #Collection of resources
    scope:
      path: ""
      type: collections
    values:
      layout: collection
      permalink: /collections/:path/
  - #Resource documents
    scope:
      path: ""
      type: documents
    values:
      layout: document
      permalink: /documents/:path/
  - #Terms in the glossary
    scope:
      path: ""
      type: glossary
    values:
      layout: "term"
      permalink: /:collection/:path/

plugins:
  - algoliasearch-jekyll
algolia:
  application_id: 'XNTLRPVD7E'
  index_name:     'CFRCR'
  settings:
    attributesToIndex:
      - title
      - icon
      - description
      - collections



# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
keep_files: [build.log]
