#Site info
title: The Collaborative FRC Resources
mobile_title: CFRCR



#Site setup
main_menu:
  -
    text: Home
    url: /
    current_if_is: / #The url of the page has to be "/" for the Home link to be darkened
  -
    text: About
    url: /about/
    current_if_is: /about/
  -
    text: Glossary
    url: /glossary/
    current_if_contains: /glossary/ #The url of the page has to contain "/glossary/" for the Glossary link to be darkened
  -
    text: Resources
    url: /resources/
    current_if_contains: /resources/

collections: #A list of all custom jekyll collections aand their variables
  glossary: #Useful terms
    output: true
  resource_collections: #Collections of different kinds of resources
    output: true
  resource_docs: #Resource documents that can be used in collections or viewed individually
    output: true

defaults: #Default values for page variables
  - #All pages
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - #Terms in the glossary
    scope:
      path: ""
      type: glossary
    values:
      layout: "term"
      permalink: /:collection/:path/
  - #Collection of resources
    scope:
      path: ""
      type: resource_collections
    values:
      layout: resource_collection
      permalink: /resources/collections/:path/
  - #Resource documents
    scope:
      path: ""
      type: resource_docs
    values:
      permalink: /resources/docs/:path/



# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
keep_files: [build.log]
